// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlHGtanylsOPDDIHEiSA4kBNVJ7jF0-Hw',
    appId: '1:848749838205:web:9aa9c44239197bd2281614',
    messagingSenderId: '848749838205',
    projectId: 'vet-route-f20a4',
    authDomain: 'vet-route-f20a4.firebaseapp.com',
    storageBucket: 'vet-route-f20a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2K1E-oxWYJ-WC5Y3BywO_0XqaNWCcB_s',
    appId: '1:848749838205:android:43b20ef791c7009c281614',
    messagingSenderId: '848749838205',
    projectId: 'vet-route-f20a4',
    storageBucket: 'vet-route-f20a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qb6RipKcg_8ocObLZRnQPmF_c3n7QTU',
    appId: '1:848749838205:ios:1b94ed32dd407564281614',
    messagingSenderId: '848749838205',
    projectId: 'vet-route-f20a4',
    storageBucket: 'vet-route-f20a4.firebasestorage.app',
    iosBundleId: 'com.example.vetRoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2qb6RipKcg_8ocObLZRnQPmF_c3n7QTU',
    appId: '1:848749838205:ios:1b94ed32dd407564281614',
    messagingSenderId: '848749838205',
    projectId: 'vet-route-f20a4',
    storageBucket: 'vet-route-f20a4.firebasestorage.app',
    iosBundleId: 'com.example.vetRoute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlHGtanylsOPDDIHEiSA4kBNVJ7jF0-Hw',
    appId: '1:848749838205:web:43d2246cc65a13c0281614',
    messagingSenderId: '848749838205',
    projectId: 'vet-route-f20a4',
    authDomain: 'vet-route-f20a4.firebaseapp.com',
    storageBucket: 'vet-route-f20a4.firebasestorage.app',
  );
}
