// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoJI6DXmPz-Qxldi04Mprgxstes8Fx1ZA',
    appId: '1:72038043623:web:996185937f85f513ee7742',
    messagingSenderId: '72038043623',
    projectId: 'vet-route-prod',
    authDomain: 'vet-route-prod.firebaseapp.com',
    storageBucket: 'vet-route-prod.firebasestorage.app',
    measurementId: 'G-YXQR7DKR6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH3y7wzkcJGpZblKbPXRzfUzX8I4u9vj4',
    appId: '1:72038043623:android:d9eed15e1e735835ee7742',
    messagingSenderId: '72038043623',
    projectId: 'vet-route-prod',
    storageBucket: 'vet-route-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeDTxrzytZZ6uwo_vX_iMl2ZDN5TqyDEE',
    appId: '1:72038043623:ios:7dfedb1c797f9beeee7742',
    messagingSenderId: '72038043623',
    projectId: 'vet-route-prod',
    storageBucket: 'vet-route-prod.firebasestorage.app',
    iosClientId: '72038043623-7tml092f9n4a5aqiatgtcgchm1cfbo39.apps.googleusercontent.com',
    iosBundleId: 'com.wescley.vetRoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeDTxrzytZZ6uwo_vX_iMl2ZDN5TqyDEE',
    appId: '1:72038043623:ios:0daedae26f6f75f2ee7742',
    messagingSenderId: '72038043623',
    projectId: 'vet-route-prod',
    storageBucket: 'vet-route-prod.firebasestorage.app',
    iosClientId: '72038043623-e00duugat4qcll79hunqkeutb3mis8lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetRoute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoJI6DXmPz-Qxldi04Mprgxstes8Fx1ZA',
    appId: '1:72038043623:web:fd1ff021b1ea6e3cee7742',
    messagingSenderId: '72038043623',
    projectId: 'vet-route-prod',
    authDomain: 'vet-route-prod.firebaseapp.com',
    storageBucket: 'vet-route-prod.firebasestorage.app',
    measurementId: 'G-4SFWEBS23L',
  );
}
